# Generated by Django 4.2.5 on 2023-11-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст письма', verbose_name='текст письма')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Время создания письма', null=True, verbose_name='время создания')),
                ('mail', models.EmailField(help_text='Введите вашу почту', max_length=254, verbose_name='почта')),
            ],
            options={
                'verbose_name': 'фидбек',
                'verbose_name_plural': 'фидбек',
            },
        ),
    ]
