# Generated by Django 4.2.5 on 2023-11-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(help_text='Введите ваше имя', max_length=200, null=True, verbose_name='имя отправителя'),
        ),
    ]
