# Generated by Django 4.2.5 on 2023-11-08 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0004_statuslog_feedback_statuslog_from_status_and_more_squashed_0006_alter_feedback_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuslog',
            options={'verbose_name': 'лог статуса', 'verbose_name_plural': 'логи статуса'},
        ),
        migrations.RemoveField(
            model_name='statuslog',
            name='to_status',
        ),
        migrations.AddField(
            model_name='statuslog',
            name='to',
            field=models.CharField(help_text='Текущий статус', max_length=12, null=True, verbose_name='текущий статус'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
