# Generated by Django 4.2.5 on 2023-11-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_statuslog_feedback_statuslog_from_status_and_more_squashed_0006_alter_feedback_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuslog',
            options={'verbose_name': 'лог статуса', 'verbose_name_plural': 'логи статуса'},
        ),
        migrations.RemoveField(
            model_name='statuslog',
            name='to_status',
        ),
        migrations.AddField(
            model_name='statuslog',
            name='to',
            field=models.CharField(help_text='Текущий статус', max_length=12, null=True, verbose_name='текущий статус'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('IN', 'в обработке'), ('GOT', 'получено'), ('OK', 'ответ дан')], default='GOT', help_text='Текущий статус полученного письма', max_length=4, verbose_name='статус обращения'),
        ),
    ]
