# Generated by Django 4.2.5 on 2023-11-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_alter_statuslog_options_remove_statuslog_to_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('GOT', 'получено'), ('IN', 'в обработке'), ('OK', 'ответ дан')], default='GOT', help_text='Текущий статус полученного письма', max_length=4, verbose_name='статус обращения'),
        ),
    ]
