# Generated by Django 4.2.5 on 2023-11-10 16:29

from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_remove_feedback_mail_remove_feedback_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=feedback.models.FeedbackFiles.get_upload_path, verbose_name='файл')),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', related_query_name='files', to='feedback.feedback', verbose_name='файл')),
            ],
        ),
    ]
