# Generated by Django 4.2.5 on 2023-11-09 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_remove_feedback_mail_remove_feedback_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/<django.db.models.fields.related.ForeignKey>')),
                ('main_feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='files', to='feedback.feedback', verbose_name='файл')),
            ],
        ),
    ]
