# Generated by Django 4.2.5 on 2023-11-09 20:04

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_feedbackfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackfiles',
            name='file',
            field=models.FileField(null=True, upload_to=feedback.models.FeedbackFiles.get_upload_path),
        ),
    ]
