# Generated by Django 4.2.5 on 2023-11-14 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, help_text='День рождения пользователя(необязательно)', null=True, verbose_name='день рождения')),
                ('image', models.ImageField(blank=True, help_text='Аватар пользователя(необязательно)', null=True, upload_to=users.models.Profile.get_avatar_path, verbose_name='аватарка')),
                ('coffee_count', models.PositiveIntegerField(default=0, help_text='Количество переходов по /coffee/', verbose_name='сварено кофе')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'дополнительное поле',
                'verbose_name_plural': 'дополнительные поля',
            },
        ),
        migrations.DeleteModel(
            name='UserProxy',
        ),
    ]
