# Generated by Django 4.2.5 on 2023-11-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attempts_count',
            field=models.PositiveIntegerField(default=0, help_text='Число неудачных попыток входа', verbose_name='попытки входа'),
        ),
    ]
