# Generated by Django 4.2.5 on 2023-11-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_attempts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reactivation_time',
            field=models.DateField(blank=True, help_text='Время преодоления порога максимального числа неудачных попыток войти', null=True, verbose_name='время деактивации аккаунта'),
        ),
    ]
