# Generated by Django 4.2.5 on 2023-10-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("catalog", "0001_initial"),
        ("catalog", "0002_delete_item"),
        ("catalog", "0003_initial"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
    ]
