# Generated by Django 4.2.5 on 2023-10-17 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
    ]
