# Generated by Django 4.2.5 on 2023-10-17 22:18

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Назовите товар, не более 150 символов",
                        max_length=150,
                        verbose_name="Название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Статус товара",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Максимальная длина 200 символов, уникальное значениерамках таблицы, только цифры буквы латиницы и символы - и _",
                        max_length=200,
                        unique=True,
                        verbose_name="Слаг",
                    ),
                ),
                (
                    "weight",
                    models.SmallIntegerField(
                        default=100,
                        help_text="От 0 до 32767, значение по-умолчанию 100, целое число",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Вес",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Назовите товар, не более 150 символов",
                        max_length=150,
                        verbose_name="Название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Статус товара",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Максимальная длина - 200 символов, уникальное значениерамках таблицы, только цифры, буквы латиницы и символы - и _",
                        max_length=200,
                        unique=True,
                        verbose_name="Слаг",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AddField(
            model_name="item",
            name="is_published",
            field=models.BooleanField(
                default=True, help_text="Статус товара", verbose_name="Опубликовано"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Описание товара, обязательно должно входить одно из слов:превосходно, роскошное",
                null=True,
                validators=[catalog.models.validate_must_contain],
                verbose_name="Текст",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                help_text="Назовите товар, не более 150 символов",
                max_length=150,
                verbose_name="Название",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.category",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(to="catalog.tag"),
        ),
    ]
