# Generated by Django 4.2.5 on 2023-10-18 13:02

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_category_tag_alter_item_options_item_is_published_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "категория", "verbose_name_plural": "категории"},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "товар", "verbose_name_plural": "товары"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "тэг", "verbose_name_plural": "тэги"},
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Не более 150 символов",
                max_length=150,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.category"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                help_text="Не более 150 символов",
                max_length=150,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Описание товара, обязательно должно входить одно из слов:превосходно, роскошное",
                validators=[catalog.models.validate_must_contain],
                verbose_name="Текст",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Не более 150 символов",
                max_length=150,
                verbose_name="Название",
            ),
        ),
    ]
