# Generated by Django 4.2.5 on 2023-10-20 18:47

from django.db import migrations, models

__all__ = ["Migration"]


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_alter_item_text_squashed_0008_alter_item_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="normalized_name",
            field=models.SlugField(
                editable=False,
                help_text="Нормализованное имя необходимое для исключения похожих названий",
                unique=True,
                verbose_name="нормализованное имя",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="normalized_name",
            field=models.SlugField(
                editable=False,
                help_text="Нормализованное имя необходимое для исключения похожих названий",
                unique=True,
                verbose_name="нормализованное имя",
            ),
        ),
    ]
