# Generated by Django 4.2.5 on 2023-10-25 23:37

from django.db import migrations, models
import django.db.models.deletion

__all__ = ["Migration"]


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0009_category_normalized_name_tag_normalized_name_squashed_0010_alter_category_normalized_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MainImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите главное изображение товара",
                        null=True,
                        upload_to="catalog/",
                        verbose_name="главное изображение",
                    ),
                ),
                (
                    "main_item",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.item",
                        verbose_name="главное изображение",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to="catalog/",
                        verbose_name="изображение к товару",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.item",
                        verbose_name="изображения к товару",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение к товару",
                "verbose_name_plural": "изображения к товару",
            },
        ),
    ]
