# Generated by Django 4.2.5 on 2023-10-25 14:31

from django.db import migrations, models

__all__ = ["Migration"]


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0009_category_normalized_name_tag_normalized_name_squashed_0010_alter_category_normalized_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="main_image",
            field=models.ImageField(
                null=True, upload_to="catalog/", verbose_name="главное изображение"
            ),
        ),
    ]
