# Generated by Django 4.2.5 on 2023-10-25 17:00

from django.db import migrations, models
import django.db.models.deletion

__all__ = ["Migration"]


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_item_main_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to="catalog/",
                        verbose_name="изображение к товару",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.item",
                        verbose_name="изображения к товару",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение к товару",
                "verbose_name_plural": "изображения к товару",
            },
        ),
    ]
