# Generated by Django 4.2.5 on 2023-10-26 00:05

from django.db import migrations, models

__all__ = ["Migration"]


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_mainimage_itemimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mainimage",
            options={
                "verbose_name": "главное изображение",
                "verbose_name_plural": "главные изображения",
            },
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="image",
            field=models.ImageField(
                help_text="Загрузите изображения в галлерею товара",
                null=True,
                upload_to="catalog/",
                verbose_name="изображение к товару",
            ),
        ),
    ]
