# Generated by Django 4.2.5 on 2023-11-03 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0013_alter_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False, help_text='Статус товара на главной странице', verbose_name='отображается на главной'),
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='main_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='catalog.item', verbose_name='главное изображение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='items', to='catalog.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_query_name='items', to='catalog.tag', verbose_name='тэги'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='normalized_name',
            field=models.SlugField(editable=False, help_text='Нормализованное имя необходимое для исключения похожих названий', null=True, unique=True, verbose_name='нормализованное имя'),
        ),
    ]
