# Generated by Django 4.2.5 on 2023-11-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False, help_text='Статус товара на главной странице', verbose_name='отображается на главной'),
        ),
    ]
