# Generated by Django 4.2.5 on 2023-11-03 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_item_is_on_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainimage',
            name='main_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='catalog.item', verbose_name='главное изображение'),
        ),
    ]
