# Generated by Django 4.2.5 on 2023-11-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_item_is_on_main_squashed_0016_alter_item_category_alter_item_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='normalized_name',
            field=models.SlugField(editable=False, help_text='Нормализованное имя необходимое для исключения похожих названий', null=True, unique=True, verbose_name='нормализованное имя'),
        ),
    ]
