# Generated by Django 4.2.5 on 2023-11-05 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_category_normalized_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Время создания товара', verbose_name='время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Время последнего обновления товара', verbose_name='время последнего обновления'),
        ),
    ]
