# Generated by Django 4.2.5 on 2023-11-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_category_normalized_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Время создания товара', null=True, verbose_name='время создания'),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Время последнего обновления товара', null=True, verbose_name='время последнего обновления'),
        ),
    ]
